### ISSUE TITLE
[Feature Request] partial trace

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/YaoArrayRegister.jl#5]
It seems we missed this one, did we?

**Comment by GiggleLiu** [comment]
Are you intended to obtain a reduced density matrix? Then it is straightforward to do with focus.

Or do you mean a general one for matrices like the following
https://github.com/ZKSI/QuantumInformation.jl/blob/c3ebbf15fdff6e3df5aca0919f6175e94c61b4cf/src/ptrace.jl#L9

**Comment by Roger-luo** [comment]
I'm writing some code about graph state, whose partial trace is calculated in a specific way, I'm not sure how to define `focus!`/`relax!` for a graph state, an interface in YaoBase that allows me to directly inherit would help.

It'll also make it easier to use for registers in general, since generally to define a quantum channel, one only need isometric operations plus partial trace.

**Comment by GiggleLiu** [comment]
Is it Possible to Show the formula?

**Comment by Roger-luo** [comment]
when the graph can be divided to a bipartite graph A, B for targeting partial trace, tr_B, this is straight forward: just remove the vertices in B. But if it's not dividable, the situation depends on whether it is a graph state anymore.

**Comment by Roger-luo** [comment]
I added a convenient one liner for `partial_tr`, it uses `focus!/relax!` by default, but overloadable, this make my life with Graph states feels easier.
