### ISSUE TITLE
Do I need to update to Julia 1.4.0? 

### ISSUE THREAD

**Issue by ywlds** [QuantumBFS/YaoArrayRegister.jl#66]
(v1.3) pkg> add YaoArrayRegister@0.7.1
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package YaoArrayRegister [e600142f]:
 YaoArrayRegister [e600142f] log:
 ├─possible versions are: [0.1.0, 0.2.0, 0.3.0-0.3.10, 0.4.0-0.4.2, 0.5.0-0.5.2, 0.6.0-0.6.2] or uninstalled
 └─restricted to versions 0.7.1 by an explicit requirement — no versions left

if I do not want to update the Julia to Julia 1.4.0, what should I do?

**Comment by Roger-luo** [comment]
can you show your `st`? I suspect you installed `YaoExtensions`. Its latest version is not compatible with 0.7.1. You need to install the master branch `add YaoExtensions#master`

**Comment by Roger-luo** [comment]
and I think you didn't run `up` before you try to install the latest versions do you?

**Comment by Roger-luo** [comment]
I'm closing this but feel free to open other issues.
