### ISSUE TITLE
Port Yao/#158

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/YaoArrayRegister.jl#7]
It seems some functions of PR: https://github.com/QuantumBFS/Yao.jl/pull/158
is missed.

I'll leave this after we release v0.4 and port them as bugfix later. This won't influence Yao at all.

- [ ] measure operators
- [ ] fix `measure` for focused register's

But I need some explanation on the `dropzeros` function.

**Comment by Roger-luo** [comment]
where did you port this? @GiggleLiu

**Comment by GiggleLiu** [comment]
`insert_qubits!` is ported in `YaoArrayRegister`.
Measure operation is scattered in `YaoBase`, `YaoArrayRegister` and `YaoBlocks`.

**Comment by Roger-luo** [comment]
YaoBase one is merged, what are the rest?

https://github.com/QuantumBFS/YaoArrayRegister.jl/pull/12

and?
