### ISSUE TITLE
register package

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/YaoArrayRegister.jl#9]
@JuliaRegistrator register()

**Comment by Roger-luo** [comment]
@JuliaRegistrator register()

**Comment by Roger-luo** [comment]
@JuliaRegistrator register()

**Comment by Roger-luo** [comment]
@JuliaRegistrator register()

**Comment by Roger-luo** [comment]
@JuliaRegistrator register()

**Comment by Roger-luo** [comment]
@JuliaRegistrator register()

**Comment by Roger-luo** [comment]
@JuliaRegistrator register()

**Comment by Roger-luo** [comment]
@JuliaRegistrator register()

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by GiggleLiu** [comment]
@JuliaRegistrator register

**Comment by GiggleLiu** [comment]
To fix julia 1.2 instruct dispatch.

@JuliaRegistrator register()

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by GiggleLiu** [comment]
@JuliaRegistrator register

**Comment by GiggleLiu** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by GiggleLiu** [comment]
There is no new feature, why 0.7.0?
